### ISSUE TITLE
Strip down library size

### ISSUE THREAD

**Issue by simonbyrne** [simonbyrne/libcg#7]
It currently weights in at 142MB.

@ViralBShah you mentioned this was possible?

**Comment by ViralBShah** [comment]
Mainly because we use all the stdlibs in the system image. @kristofferC is there a user-accessible way to make a smaller one?

**Comment by ViralBShah** [comment]
Eventually, we need the tree shaking to really strip these.

**Comment by KristofferC** [comment]
There is a `filter_stdlibs` option that removes stdlibs that is not in the Manifest. The size also depends on how much code gets compiled into it.

**Comment by ViralBShah** [comment]
The Manifest has InteractiveUtils, Markdown, Sockets - none of which seem relevant here. Where might they be coming from?

**Comment by simonbyrne** [comment]
> The Manifest has InteractiveUtils, Markdown, Sockets - none of which seem relevant here. Where might they be coming from?

It's because I have PackageCompiler.jl in the same Manifest. I'll split them out.

**Comment by simonbyrne** [comment]
Doing these two seems to cut it down by a factor of 1/2 (140MB -> 70MB): https://github.com/simonbyrne/libcg/pull/12
